import { LinearClient } from '@linear/sdk';
import { ProposedIssue } from '@/types/proposal';
import { updateProposal } from './db';

let linearClient: LinearClient | null = null;
let cachedTeamId: string | null = null;

function getLinearClient(): LinearClient {
  if (!linearClient) {
    const apiKey = process.env.LINEAR_API_KEY;
    if (!apiKey) {
      throw new Error('LINEAR_API_KEY is not set');
    }
    linearClient = new LinearClient({ apiKey });
  }
  return linearClient;
}

// Get the actual team ID (UUID) from the team key (e.g., "UND")
async function getTeamId(): Promise<string> {
  if (cachedTeamId) {
    return cachedTeamId;
  }

  const teamKey = process.env.LINEAR_TEAM_ID;
  if (!teamKey) {
    throw new Error('LINEAR_TEAM_ID is not set');
  }

  const client = getLinearClient();
  const teams = await client.teams();

  // Find the team by key (the short identifier like "UND")
  const team = teams.nodes.find(t => t.key === teamKey);

  if (!team) {
    // If not found by key, maybe they provided the actual ID
    const teamById = teams.nodes.find(t => t.id === teamKey);
    if (teamById) {
      cachedTeamId = teamById.id;
      return cachedTeamId;
    }
    throw new Error(`Team with key "${teamKey}" not found`);
  }

  cachedTeamId = team.id;
  return cachedTeamId;
}

const SEVERITY_TO_PRIORITY: Record<string, number> = {
  critical: 1, // Urgent
  high: 2,     // High
  medium: 3,   // Medium
  low: 4,      // Low
};

const CATEGORY_LABELS: Record<string, string> = {
  security: '🔒 Security',
  testing: '🧪 Testing',
};

export async function createLinearIssue(proposal: ProposedIssue): Promise<{
  issueId: string;
  issueUrl: string;
}> {
  const client = getLinearClient();
  const teamId = await getTeamId();

  // Build issue description with all relevant info
  const description = buildIssueDescription(proposal);

  // Create the issue
  const issuePayload = await client.createIssue({
    teamId,
    title: `[${CATEGORY_LABELS[proposal.category]}] ${proposal.title}`,
    description,
    priority: SEVERITY_TO_PRIORITY[proposal.severity] || 3,
  });

  const issue = await issuePayload.issue;

  if (!issue) {
    throw new Error('Failed to create Linear issue');
  }

  const issueId = issue.id;
  const issueUrl = `https://linear.app/issue/${issue.identifier}`;

  // Update proposal with Linear info
  updateProposal({
    id: proposal.id,
    status: 'approved',
    linearIssueId: issueId,
    linearIssueUrl: issueUrl,
  });

  return { issueId, issueUrl };
}

function buildIssueDescription(proposal: ProposedIssue): string {
  const parts: string[] = [];

  // Header with category and severity
  parts.push(`**Category:** ${CATEGORY_LABELS[proposal.category]}`);
  parts.push(`**Severity:** ${proposal.severity.toUpperCase()}`);
  parts.push(`**File:** \`${proposal.filePath}\``);

  if (proposal.lineNumbers) {
    parts.push(`**Lines:** ${proposal.lineNumbers.start}-${proposal.lineNumbers.end}`);
  }

  parts.push('');
  parts.push('---');
  parts.push('');

  // Main description
  parts.push('## Description');
  parts.push(proposal.description);
  parts.push('');

  // Code snippet
  if (proposal.codeSnippet) {
    parts.push('## Code');
    parts.push('```');
    parts.push(proposal.codeSnippet);
    parts.push('```');
    parts.push('');
  }

  // Rationale
  parts.push('## Why This Matters');
  parts.push(proposal.rationale);
  parts.push('');

  // Suggested fix
  if (proposal.suggestedFix) {
    parts.push('## Suggested Fix');
    parts.push(proposal.suggestedFix);
    parts.push('');
  }

  // Footer
  parts.push('---');
  parts.push('*Generated by AI-powered code analysis*');

  return parts.join('\n');
}

export async function getTeams(): Promise<{ id: string; name: string }[]> {
  const client = getLinearClient();
  const teams = await client.teams();

  return teams.nodes.map(team => ({
    id: team.id,
    name: team.name,
  }));
}

export async function validateConnection(): Promise<boolean> {
  try {
    const client = getLinearClient();
    const viewer = await client.viewer;
    return !!viewer.id;
  } catch {
    return false;
  }
}

export interface ExistingIssue {
  id: string;
  identifier: string;
  title: string;
  url: string;
}

// Search for existing issues that might match a proposed issue
export async function findExistingIssue(
  title: string,
  filePath: string
): Promise<ExistingIssue | null> {
  try {
    const client = getLinearClient();
    const teamId = await getTeamId();

    // Search for issues with similar title or file path
    // Linear's search is fuzzy, so we search for key terms
    const searchTerms = [
      // Try searching for the file path
      filePath.split('/').pop() || '',
      // Try key words from title
      ...title.split(' ').filter(w => w.length > 4).slice(0, 3),
    ].filter(Boolean);

    for (const term of searchTerms) {
      if (!term || term.length < 3) continue;

      const results = await client.issueSearch({ query: term });

      for (const issue of results.nodes) {
        // Check if this issue is from the same team
        const issueTeam = await issue.team;
        if (issueTeam?.id !== teamId) continue;

        // Check for similarity - title contains our title or vice versa
        const issueTitle = issue.title.toLowerCase();
        const proposedTitle = title.toLowerCase();

        // Check if titles are similar (one contains the other, or high word overlap)
        const titleMatch =
          issueTitle.includes(proposedTitle) ||
          proposedTitle.includes(issueTitle) ||
          calculateSimilarity(issueTitle, proposedTitle) > 0.6;

        // Check if file path is mentioned
        const description = issue.description || '';
        const fileMatch = description.toLowerCase().includes(filePath.toLowerCase());

        if (titleMatch || fileMatch) {
          return {
            id: issue.id,
            identifier: issue.identifier,
            title: issue.title,
            url: `https://linear.app/issue/${issue.identifier}`,
          };
        }
      }
    }

    return null;
  } catch (error) {
    console.error('Error searching for existing issues:', error);
    return null;
  }
}

// Simple word-based similarity calculation
function calculateSimilarity(str1: string, str2: string): number {
  const words1 = new Set(str1.split(/\s+/).filter(w => w.length > 2));
  const words2 = new Set(str2.split(/\s+/).filter(w => w.length > 2));

  if (words1.size === 0 || words2.size === 0) return 0;

  let matches = 0;
  Array.from(words1).forEach(word => {
    if (words2.has(word)) matches++;
  });

  return matches / Math.max(words1.size, words2.size);
}
