import { LinearClient } from '@linear/sdk';
import { createClient } from '@/lib/supabase/server';
import { decrypt } from '@/lib/encryption';
import type { ProposedIssue } from '@/types/proposal';

const SEVERITY_TO_PRIORITY: Record<string, number> = {
  critical: 1, // Urgent
  high: 2,     // High
  medium: 3,   // Medium
  low: 4,      // Low
};

const CATEGORY_LABELS: Record<string, string> = {
  security: '🔒 Security',
  testing: '🧪 Testing',
};

/**
 * Get a Linear client for a workspace
 * This decrypts the stored OAuth token and creates a LinearClient instance
 */
export async function getLinearClient(workspaceId: string): Promise<LinearClient | null> {
  const supabase = await createClient();

  const result = await supabase
    .from('linear_connections')
    .select('access_token_encrypted, expires_at')
    .eq('workspace_id', workspaceId)
    .limit(1)
    .single();

  const connection = result.data as { access_token_encrypted: string; expires_at: string | null } | null;

  if (result.error || !connection) {
    console.error('No Linear connection found for workspace:', workspaceId);
    return null;
  }

  // Check if token is expired
  if (connection.expires_at && new Date(connection.expires_at) < new Date()) {
    console.error('Linear token has expired for workspace:', workspaceId);
    // TODO: Implement token refresh
    return null;
  }

  try {
    const accessToken = decrypt(connection.access_token_encrypted);
    return new LinearClient({ accessToken });
  } catch (error) {
    console.error('Failed to decrypt Linear token:', error);
    return null;
  }
}

/**
 * Get the default team ID for a workspace
 * Falls back to the first available team if no default is set
 */
export async function getDefaultTeamId(
  linearClient: LinearClient,
  workspaceId: string
): Promise<string | null> {
  const supabase = await createClient();

  // Check for saved default team
  const result = await supabase
    .from('linear_settings')
    .select('default_team_id')
    .eq('workspace_id', workspaceId)
    .single();

  const settings = result.data as { default_team_id: string | null } | null;

  if (settings?.default_team_id) {
    return settings.default_team_id;
  }

  // Fall back to first team
  try {
    const teams = await linearClient.teams();
    if (teams.nodes.length > 0) {
      return teams.nodes[0].id;
    }
  } catch (error) {
    console.error('Failed to fetch Linear teams:', error);
  }

  return null;
}

/**
 * Create a Linear issue from a proposal
 */
export async function createLinearIssue(
  linearClient: LinearClient,
  teamId: string,
  proposal: ProposedIssue
): Promise<{ issueId: string; issueUrl: string }> {
  const description = buildIssueDescription(proposal);

  const issuePayload = await linearClient.createIssue({
    teamId,
    title: `[${CATEGORY_LABELS[proposal.category]}] ${proposal.title}`,
    description,
    priority: SEVERITY_TO_PRIORITY[proposal.severity] || 3,
  });

  const issue = await issuePayload.issue;

  if (!issue) {
    throw new Error('Failed to create Linear issue');
  }

  return {
    issueId: issue.id,
    issueUrl: `https://linear.app/issue/${issue.identifier}`,
  };
}

function buildIssueDescription(proposal: ProposedIssue): string {
  const parts: string[] = [];

  // Header with category and severity
  parts.push(`**Category:** ${CATEGORY_LABELS[proposal.category]}`);
  parts.push(`**Severity:** ${proposal.severity.toUpperCase()}`);
  parts.push(`**File:** \`${proposal.filePath}\``);

  if (proposal.lineNumbers) {
    parts.push(`**Lines:** ${proposal.lineNumbers.start}-${proposal.lineNumbers.end}`);
  }

  parts.push('');
  parts.push('---');
  parts.push('');

  // Main description
  parts.push('## Description');
  parts.push(proposal.description);
  parts.push('');

  // Code snippet
  if (proposal.codeSnippet) {
    parts.push('## Code');
    parts.push('```');
    parts.push(proposal.codeSnippet);
    parts.push('```');
    parts.push('');
  }

  // Rationale
  parts.push('## Why This Matters');
  parts.push(proposal.rationale);
  parts.push('');

  // Suggested fix
  if (proposal.suggestedFix) {
    parts.push('## Suggested Fix');
    parts.push(proposal.suggestedFix);
    parts.push('');
  }

  // Footer
  parts.push('---');
  parts.push('*Generated by AI-powered code analysis*');

  return parts.join('\n');
}

/**
 * Get available teams from Linear
 */
export async function getTeams(
  linearClient: LinearClient
): Promise<{ id: string; key: string; name: string }[]> {
  try {
    const teams = await linearClient.teams();
    return teams.nodes.map(team => ({
      id: team.id,
      key: team.key,
      name: team.name,
    }));
  } catch (error) {
    console.error('Failed to fetch Linear teams:', error);
    return [];
  }
}

/**
 * Validate Linear connection
 */
export async function validateConnection(linearClient: LinearClient): Promise<boolean> {
  try {
    const viewer = await linearClient.viewer;
    return !!viewer.id;
  } catch {
    return false;
  }
}

export interface ExistingIssue {
  id: string;
  identifier: string;
  title: string;
  url: string;
}

/**
 * Search for existing issues that might match a proposed issue
 */
export async function findExistingIssue(
  linearClient: LinearClient,
  teamId: string,
  title: string,
  filePath: string
): Promise<ExistingIssue | null> {
  try {
    // Search for issues with similar title or file path
    const searchTerms = [
      filePath.split('/').pop() || '',
      ...title.split(' ').filter(w => w.length > 4).slice(0, 3),
    ].filter(Boolean);

    for (const term of searchTerms) {
      if (!term || term.length < 3) continue;

      const results = await linearClient.issueSearch({ query: term });

      for (const issue of results.nodes) {
        const issueTeam = await issue.team;
        if (issueTeam?.id !== teamId) continue;

        const issueTitle = issue.title.toLowerCase();
        const proposedTitle = title.toLowerCase();

        const titleMatch =
          issueTitle.includes(proposedTitle) ||
          proposedTitle.includes(issueTitle) ||
          calculateSimilarity(issueTitle, proposedTitle) > 0.6;

        const description = issue.description || '';
        const fileMatch = description.toLowerCase().includes(filePath.toLowerCase());

        if (titleMatch || fileMatch) {
          return {
            id: issue.id,
            identifier: issue.identifier,
            title: issue.title,
            url: `https://linear.app/issue/${issue.identifier}`,
          };
        }
      }
    }

    return null;
  } catch (error) {
    console.error('Error searching for existing issues:', error);
    return null;
  }
}

function calculateSimilarity(str1: string, str2: string): number {
  const words1 = new Set(str1.split(/\s+/).filter(w => w.length > 2));
  const words2 = new Set(str2.split(/\s+/).filter(w => w.length > 2));

  if (words1.size === 0 || words2.size === 0) return 0;

  let matches = 0;
  Array.from(words1).forEach(word => {
    if (words2.has(word)) matches++;
  });

  return matches / Math.max(words1.size, words2.size);
}
